//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrms_PakAsia.Pages.Organization
{


    public partial class AuditLogs
    {

        protected global::System.Web.UI.WebControls.TextBox txtUser;

        protected global::System.Web.UI.WebControls.TextBox txtModule;

        protected global::System.Web.UI.WebControls.TextBox txtAction;

        protected global::System.Web.UI.WebControls.TextBox txtIP;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        protected global::System.Web.UI.WebControls.Button btnFilter;

        protected global::System.Web.UI.WebControls.Button btnClear;

        protected global::System.Web.UI.WebControls.GridView gvLogs;
    }
}

